### ISSUE TITLE
SSR async component Throw an error  "Cannot add property _Ctor, object is not extensible"

### ISSUE THREAD

**Issue by lzxb** [vitejs/vite-plugin-vue2#20]
```bash
TypeError: Cannot add property _Ctor, object is not extensible
    at Function.Vue.extend (/Volumes/work/github/lzxb/vite-vue2-ssr/node_modules/vue/dist/vue.runtime.common.dev.js:5557:73)
    at createComponent (/Volumes/work/github/lzxb/vite-vue2-ssr/node_modules/vue-server-renderer/build.dev.js:1896:25)
    at resolve (/Volumes/work/github/lzxb/vite-vue2-ssr/node_modules/vue-server-renderer/build.dev.js:7207:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Code screenshot

<img width="632" alt="image" src="https://user-images.githubusercontent.com/8424643/177703369-8658f561-f660-4dd1-89f3-c8de3b3023e0.png">

<img width="841" alt="image" src="https://user-images.githubusercontent.com/8424643/177704211-65b1126f-1d0e-4394-be33-2fb124cffd69.png">

<img width="893" alt="image" src="https://user-images.githubusercontent.com/8424643/177704347-6d06a3b1-4ff0-43a4-9a79-894a541e6818.png">

Recurrence
https://github.com/lzxb/vite-vue2-ssr
```bash
yarn 
yarn build
yarn start
# Open http://localhost:3000
```

**Comment by Anubarak** [comment]
I have the very same issue... any progress here?
